configuracion de CI v2.3

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,4 +1,5 @@
 name: Testing
+
 on: 
   push:
     branches: [ "main" ]
@@ -13,17 +14,22 @@ jobs:
       matrix:
         python-version: [3.7, 3.8, 3.9]
     steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v3
-      with:
-        python-version: ${{ matrix.python-version }}
+      - name: Checkout code
+        uses: actions/checkout@v4
         
-    - name: Instalar dependencias
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt || echo "Some dependencies failed to install"
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v3
+        with:
+          python-version: ${{ matrix.python-version }}
+        
+      - name: Debug - Imprimir requerimientos
+        run: cat requirements.txt
       
-    - name: Ejecutar Tests
-      run: |
-        python3 manage.py test
+      - name: Instalar dependencias
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt || echo "Some dependencies failed to install"
+      
+      - name: Run tests
+        run: |
+          python3 manage.py test
